apiVersion: v1
kind: Pod
metadata:
  name: busybox-loganclark
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    resources:
      requests:
        cpu: .125
        memory: "500Mi"
      limits:
        cpu: .125
        memory: "600Mi"
    imagePullPolicy: IfNotPresent
    name: busybox-loganclark
  restartPolicy: Always