apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggs44
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggs44
  template:
    metadata:
      name: loggs44
      labels: 
        app: loggs44
    spec:
      containers:
      - name: loggs44
        image: loggs44/cit270-lc
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.logan

apiVersion: v1
kind: Service
metadata:
  name: loggs44-loadbalancer
spec:
  selector: 
    app: loggs44
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443